"""Response models for /api/analyze.

WHY THESE EXIST
---------------
Two jobs, both about trust:

1. **They are the contract with the model.** Each model here is converted to a
   JSON Schema and handed to the LLM as a structured-output format, so the
   model must return exactly these fields. That removes a whole class of
   "the AI returned prose instead of JSON" failures.

2. **They are the contract with the frontend.** FastAPI validates every
   response against them, so the UI can rely on the shape.

HONESTY BY CONSTRUCTION
-----------------------
Every section carries a way to say "the paper does not contain this".
`insufficient_evidence` is not decoration - it is the mechanism that lets the
model decline instead of inventing, which root CLAUDE.md section 5 requires.
"""

from pydantic import BaseModel, ConfigDict, Field

# extra="forbid" makes Pydantic emit `additionalProperties: false`, which
# strict structured-output modes require.
_STRICT = ConfigDict(extra="forbid")


class ResearchGap(BaseModel):
    """One identified gap, with the evidence that supports calling it a gap."""

    model_config = _STRICT

    gap: str = Field(description="The gap, stated in one or two sentences.")
    why_it_matters: str = Field(description="Why addressing this gap would be valuable.")
    evidence: str = Field(
        description=(
            "The wording FROM THE PAPER that supports this gap - a short quote "
            "or close paraphrase. If the paper only implies it, say so here."
        )
    )


class Summary(BaseModel):
    """Structured summary of a single paper."""

    model_config = _STRICT

    research_problem: str = Field(description="The problem or background the paper addresses.")
    methodology: str = Field(description="How the research was carried out.")
    key_findings: list[str] = Field(description="The paper's main findings.")
    conclusion: str = Field(description="What the authors conclude.")
    insufficient_evidence: list[str] = Field(
        description=(
            "Names of any section above that the paper did not contain enough "
            "information to fill in honestly. Empty when all were covered."
        ),
    )


class ResearchGaps(BaseModel):
    """Limitations and gaps, grounded in the paper's own text."""

    model_config = _STRICT

    stated_limitations: list[str] = Field(description="Limitations the authors state themselves.")
    identified_gaps: list[ResearchGap] = Field(description="Gaps supported by the paper's content.")
    insufficient_evidence: bool = Field(
        description="True when the paper does not support any gap analysis.",
    )
    evidence_note: str = Field(
        description=("Explanation when insufficient_evidence is true; empty string otherwise."),
    )


class LiteratureReview(BaseModel):
    """A literature review built from the related work discussed IN this paper.

    ⚠️ SCOPE: with a single uploaded paper, the only literature evidence
    available is what that paper itself reports about prior work. This is a
    review of that discussion - NOT a survey of the field, which would require
    a corpus the system does not have. `scope_note` states this to the reader
    so the output is never mistaken for something broader.
    """

    model_config = _STRICT

    scope_note: str = Field(
        description=(
            "One sentence stating that this review is drawn only from the "
            "related work discussed within the uploaded paper."
        )
    )
    major_themes: list[str] = Field(description="Themes in the prior work discussed.")
    relevant_findings: list[str] = Field(
        description="Findings attributed to prior work IN the paper."
    )
    comparisons: list[str] = Field(
        description=(
            "Comparisons between studies, ONLY where the paper actually makes "
            "them. Empty if the paper makes no comparisons."
        ),
    )
    research_trends: list[str] = Field(description="Trends the paper describes.")
    limitations: list[str] = Field(description="Limitations of the prior work discussed.")
    future_directions: list[str] = Field(description="Directions the paper points toward.")
    insufficient_evidence: bool = Field(
        description=("True when the paper discusses too little prior work to review."),
    )


class DocumentInfo(BaseModel):
    """Facts about the uploaded file. Measured, never generated by the model."""

    model_config = _STRICT

    filename: str
    page_count: int
    extracted_characters: int
    chunk_count: int = Field(description="1 when the paper was analysed whole; >1 when chunked.")
    truncated: bool = Field(description="True if content had to be dropped.")


class AnalysisResponse(BaseModel):
    """The full payload returned by POST /api/analyze."""

    model_config = _STRICT

    document: DocumentInfo
    summary: Summary
    research_gaps: ResearchGaps
    literature_review: LiteratureReview
    model_used: str = Field(description="LLM model that produced the analysis.")
